// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RpgGame.Data;

#nullable disable

namespace RpgGame.Data.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20230619184201_items_and_inventories")]
    partial class items_and_inventories
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("GAME")
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence("ItemPrototypeSequence");

            modelBuilder.Entity("RpgGame.Models.Entity.Character", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(20,0)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"));

                    b.Property<int>("Class")
                        .HasColumnType("int");

                    b.Property<decimal>("CreationDate")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("Dexterity")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("Experience")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("Intelligence")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("InventoryId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<long>("Level")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("RequiredExperience")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("Strength")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("UserId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("Vitality")
                        .HasColumnType("decimal(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("UserId");

                    b.ToTable("Characters", "GAME");
                });

            modelBuilder.Entity("RpgGame.Models.Entity.Inventory", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(20,0)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"));

                    b.Property<decimal>("CharacterId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<byte>("InventoryPages")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("Money")
                        .HasColumnType("decimal(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId")
                        .IsUnique();

                    b.ToTable("Inventories", "GAME");
                });

            modelBuilder.Entity("RpgGame.Models.Entity.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<decimal>("InventoryId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("ItemPrototypeId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InventoryId");

                    b.HasIndex("ItemPrototypeId");

                    b.ToTable("Items", "GAME");
                });

            modelBuilder.Entity("RpgGame.Models.Entity.ItemPrototype", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(20,0)")
                        .HasDefaultValueSql("NEXT VALUE FOR [GAME].[ItemPrototypeSequence]");

                    SqlServerPropertyBuilderExtensions.UseSequence(b.Property<decimal>("Id"));

                    b.Property<bool>("IsEquippable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRarityDepend")
                        .HasColumnType("bit");

                    b.Property<bool>("IsStackable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTradable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUpgradable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUsable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("RequiredLevel")
                        .HasColumnType("bigint");

                    b.Property<byte>("UpgradeLevel")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(20,0)");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("RpgGame.Models.Entity.User", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(20,0)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"));

                    b.Property<byte>("CharacterSlots")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("CreationDate")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("bit");

                    b.Property<decimal>("LastLoginDate")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", "GAME");
                });

            modelBuilder.Entity("RpgGame.Models.Entity.ArmorPrototype", b =>
                {
                    b.HasBaseType("RpgGame.Models.Entity.ItemPrototype");

                    b.Property<long>("DefenseValue")
                        .HasColumnType("bigint");

                    b.Property<int>("EquippableBy")
                        .HasColumnType("int");

                    b.ToTable("ArmorPrototypes", "GAME");

                    b.HasData(
                        new
                        {
                            Id = 13000m,
                            IsEquippable = true,
                            IsRarityDepend = true,
                            IsStackable = false,
                            IsTradable = true,
                            IsUpgradable = true,
                            IsUsable = false,
                            Name = "Scratched Armor",
                            RequiredLevel = 0L,
                            UpgradeLevel = (byte)0,
                            Value = 10m,
                            DefenseValue = 10L,
                            EquippableBy = 0
                        },
                        new
                        {
                            Id = 13001m,
                            IsEquippable = true,
                            IsRarityDepend = true,
                            IsStackable = false,
                            IsTradable = true,
                            IsUpgradable = true,
                            IsUsable = false,
                            Name = "Scratched Armor +1",
                            RequiredLevel = 0L,
                            UpgradeLevel = (byte)1,
                            Value = 50m,
                            DefenseValue = 16L,
                            EquippableBy = 0
                        },
                        new
                        {
                            Id = 13002m,
                            IsEquippable = true,
                            IsRarityDepend = true,
                            IsStackable = false,
                            IsTradable = true,
                            IsUpgradable = true,
                            IsUsable = false,
                            Name = "Scratched Armor +2",
                            RequiredLevel = 0L,
                            UpgradeLevel = (byte)2,
                            Value = 100m,
                            DefenseValue = 22L,
                            EquippableBy = 0
                        },
                        new
                        {
                            Id = 13003m,
                            IsEquippable = true,
                            IsRarityDepend = true,
                            IsStackable = false,
                            IsTradable = true,
                            IsUpgradable = true,
                            IsUsable = false,
                            Name = "Scratched Armor +3",
                            RequiredLevel = 0L,
                            UpgradeLevel = (byte)3,
                            Value = 150m,
                            DefenseValue = 28L,
                            EquippableBy = 0
                        },
                        new
                        {
                            Id = 13004m,
                            IsEquippable = true,
                            IsRarityDepend = true,
                            IsStackable = false,
                            IsTradable = true,
                            IsUpgradable = true,
                            IsUsable = false,
                            Name = "Scratched Armor +4",
                            RequiredLevel = 0L,
                            UpgradeLevel = (byte)4,
                            Value = 200m,
                            DefenseValue = 34L,
                            EquippableBy = 0
                        },
                        new
                        {
                            Id = 13005m,
                            IsEquippable = true,
                            IsRarityDepend = true,
                            IsStackable = false,
                            IsTradable = true,
                            IsUpgradable = true,
                            IsUsable = false,
                            Name = "Scratched Armor +5",
                            RequiredLevel = 0L,
                            UpgradeLevel = (byte)5,
                            Value = 250m,
                            DefenseValue = 40L,
                            EquippableBy = 0
                        },
                        new
                        {
                            Id = 13006m,
                            IsEquippable = true,
                            IsRarityDepend = true,
                            IsStackable = false,
                            IsTradable = true,
                            IsUpgradable = true,
                            IsUsable = false,
                            Name = "Scratched Armor +6",
                            RequiredLevel = 0L,
                            UpgradeLevel = (byte)6,
                            Value = 300m,
                            DefenseValue = 46L,
                            EquippableBy = 0
                        },
                        new
                        {
                            Id = 13007m,
                            IsEquippable = true,
                            IsRarityDepend = true,
                            IsStackable = false,
                            IsTradable = true,
                            IsUpgradable = true,
                            IsUsable = false,
                            Name = "Scratched Armor +7",
                            RequiredLevel = 0L,
                            UpgradeLevel = (byte)7,
                            Value = 350m,
                            DefenseValue = 52L,
                            EquippableBy = 0
                        },
                        new
                        {
                            Id = 13008m,
                            IsEquippable = true,
                            IsRarityDepend = true,
                            IsStackable = false,
                            IsTradable = true,
                            IsUpgradable = true,
                            IsUsable = false,
                            Name = "Scratched Armor +8",
                            RequiredLevel = 0L,
                            UpgradeLevel = (byte)5,
                            Value = 400m,
                            DefenseValue = 58L,
                            EquippableBy = 0
                        },
                        new
                        {
                            Id = 13009m,
                            IsEquippable = true,
                            IsRarityDepend = true,
                            IsStackable = false,
                            IsTradable = true,
                            IsUpgradable = true,
                            IsUsable = false,
                            Name = "Scratched Armor +9",
                            RequiredLevel = 0L,
                            UpgradeLevel = (byte)9,
                            Value = 450m,
                            DefenseValue = 64L,
                            EquippableBy = 0
                        },
                        new
                        {
                            Id = 17000m,
                            IsEquippable = true,
                            IsRarityDepend = true,
                            IsStackable = false,
                            IsTradable = true,
                            IsUpgradable = true,
                            IsUsable = false,
                            Name = "Scratched Tunic",
                            RequiredLevel = 0L,
                            UpgradeLevel = (byte)0,
                            Value = 10m,
                            DefenseValue = 10L,
                            EquippableBy = 1
                        },
                        new
                        {
                            Id = 17001m,
                            IsEquippable = true,
                            IsRarityDepend = true,
                            IsStackable = false,
                            IsTradable = true,
                            IsUpgradable = true,
                            IsUsable = false,
                            Name = "Scratched Tunic +1",
                            RequiredLevel = 0L,
                            UpgradeLevel = (byte)1,
                            Value = 50m,
                            DefenseValue = 16L,
                            EquippableBy = 1
                        },
                        new
                        {
                            Id = 17002m,
                            IsEquippable = true,
                            IsRarityDepend = true,
                            IsStackable = false,
                            IsTradable = true,
                            IsUpgradable = true,
                            IsUsable = false,
                            Name = "Scratched Tunic +2",
                            RequiredLevel = 0L,
                            UpgradeLevel = (byte)2,
                            Value = 100m,
                            DefenseValue = 22L,
                            EquippableBy = 1
                        },
                        new
                        {
                            Id = 17003m,
                            IsEquippable = true,
                            IsRarityDepend = true,
                            IsStackable = false,
                            IsTradable = true,
                            IsUpgradable = true,
                            IsUsable = false,
                            Name = "Scratched Tunic +3",
                            RequiredLevel = 0L,
                            UpgradeLevel = (byte)3,
                            Value = 150m,
                            DefenseValue = 28L,
                            EquippableBy = 1
                        },
                        new
                        {
                            Id = 17004m,
                            IsEquippable = true,
                            IsRarityDepend = true,
                            IsStackable = false,
                            IsTradable = true,
                            IsUpgradable = true,
                            IsUsable = false,
                            Name = "Scratched Tunic +4",
                            RequiredLevel = 0L,
                            UpgradeLevel = (byte)4,
                            Value = 200m,
                            DefenseValue = 34L,
                            EquippableBy = 1
                        },
                        new
                        {
                            Id = 17005m,
                            IsEquippable = true,
                            IsRarityDepend = true,
                            IsStackable = false,
                            IsTradable = true,
                            IsUpgradable = true,
                            IsUsable = false,
                            Name = "Scratched Tunic +5",
                            RequiredLevel = 0L,
                            UpgradeLevel = (byte)5,
                            Value = 250m,
                            DefenseValue = 40L,
                            EquippableBy = 1
                        },
                        new
                        {
                            Id = 17006m,
                            IsEquippable = true,
                            IsRarityDepend = true,
                            IsStackable = false,
                            IsTradable = true,
                            IsUpgradable = true,
                            IsUsable = false,
                            Name = "Scratched Tunic +6",
                            RequiredLevel = 0L,
                            UpgradeLevel = (byte)6,
                            Value = 300m,
                            DefenseValue = 46L,
                            EquippableBy = 1
                        },
                        new
                        {
                            Id = 17007m,
                            IsEquippable = true,
                            IsRarityDepend = true,
                            IsStackable = false,
                            IsTradable = true,
                            IsUpgradable = true,
                            IsUsable = false,
                            Name = "Scratched Tunic +7",
                            RequiredLevel = 0L,
                            UpgradeLevel = (byte)7,
                            Value = 350m,
                            DefenseValue = 52L,
                            EquippableBy = 1
                        },
                        new
                        {
                            Id = 17008m,
                            IsEquippable = true,
                            IsRarityDepend = true,
                            IsStackable = false,
                            IsTradable = true,
                            IsUpgradable = true,
                            IsUsable = false,
                            Name = "Scratched Tunic +8",
                            RequiredLevel = 0L,
                            UpgradeLevel = (byte)5,
                            Value = 400m,
                            DefenseValue = 58L,
                            EquippableBy = 1
                        },
                        new
                        {
                            Id = 17009m,
                            IsEquippable = true,
                            IsRarityDepend = true,
                            IsStackable = false,
                            IsTradable = true,
                            IsUpgradable = true,
                            IsUsable = false,
                            Name = "Scratched Tunic +9",
                            RequiredLevel = 0L,
                            UpgradeLevel = (byte)9,
                            Value = 450m,
                            DefenseValue = 64L,
                            EquippableBy = 1
                        },
                        new
                        {
                            Id = 21000m,
                            IsEquippable = true,
                            IsRarityDepend = true,
                            IsStackable = false,
                            IsTradable = true,
                            IsUpgradable = true,
                            IsUsable = false,
                            Name = "Scratched Robe",
                            RequiredLevel = 0L,
                            UpgradeLevel = (byte)0,
                            Value = 10m,
                            DefenseValue = 10L,
                            EquippableBy = 2
                        },
                        new
                        {
                            Id = 21001m,
                            IsEquippable = true,
                            IsRarityDepend = true,
                            IsStackable = false,
                            IsTradable = true,
                            IsUpgradable = true,
                            IsUsable = false,
                            Name = "Scratched Robe +1",
                            RequiredLevel = 0L,
                            UpgradeLevel = (byte)1,
                            Value = 50m,
                            DefenseValue = 16L,
                            EquippableBy = 2
                        },
                        new
                        {
                            Id = 21002m,
                            IsEquippable = true,
                            IsRarityDepend = true,
                            IsStackable = false,
                            IsTradable = true,
                            IsUpgradable = true,
                            IsUsable = false,
                            Name = "Scratched Robe +2",
                            RequiredLevel = 0L,
                            UpgradeLevel = (byte)2,
                            Value = 100m,
                            DefenseValue = 22L,
                            EquippableBy = 2
                        },
                        new
                        {
                            Id = 21003m,
                            IsEquippable = true,
                            IsRarityDepend = true,
                            IsStackable = false,
                            IsTradable = true,
                            IsUpgradable = true,
                            IsUsable = false,
                            Name = "Scratched Robe +3",
                            RequiredLevel = 0L,
                            UpgradeLevel = (byte)3,
                            Value = 150m,
                            DefenseValue = 28L,
                            EquippableBy = 2
                        },
                        new
                        {
                            Id = 21004m,
                            IsEquippable = true,
                            IsRarityDepend = true,
                            IsStackable = false,
                            IsTradable = true,
                            IsUpgradable = true,
                            IsUsable = false,
                            Name = "Scratched Robe +4",
                            RequiredLevel = 0L,
                            UpgradeLevel = (byte)4,
                            Value = 200m,
                            DefenseValue = 34L,
                            EquippableBy = 2
                        },
                        new
                        {
                            Id = 21005m,
                            IsEquippable = true,
                            IsRarityDepend = true,
                            IsStackable = false,
                            IsTradable = true,
                            IsUpgradable = true,
                            IsUsable = false,
                            Name = "Scratched Robe +5",
                            RequiredLevel = 0L,
                            UpgradeLevel = (byte)5,
                            Value = 250m,
                            DefenseValue = 40L,
                            EquippableBy = 2
                        },
                        new
                        {
                            Id = 21006m,
                            IsEquippable = true,
                            IsRarityDepend = true,
                            IsStackable = false,
                            IsTradable = true,
                            IsUpgradable = true,
                            IsUsable = false,
                            Name = "Scratched Robe +6",
                            RequiredLevel = 0L,
                            UpgradeLevel = (byte)6,
                            Value = 300m,
                            DefenseValue = 46L,
                            EquippableBy = 2
                        },
                        new
                        {
                            Id = 21007m,
                            IsEquippable = true,
                            IsRarityDepend = true,
                            IsStackable = false,
                            IsTradable = true,
                            IsUpgradable = true,
                            IsUsable = false,
                            Name = "Scratched Robe +7",
                            RequiredLevel = 0L,
                            UpgradeLevel = (byte)7,
                            Value = 350m,
                            DefenseValue = 52L,
                            EquippableBy = 2
                        },
                        new
                        {
                            Id = 21008m,
                            IsEquippable = true,
                            IsRarityDepend = true,
                            IsStackable = false,
                            IsTradable = true,
                            IsUpgradable = true,
                            IsUsable = false,
                            Name = "Scratched Robe +8",
                            RequiredLevel = 0L,
                            UpgradeLevel = (byte)5,
                            Value = 400m,
                            DefenseValue = 58L,
                            EquippableBy = 2
                        },
                        new
                        {
                            Id = 21009m,
                            IsEquippable = true,
                            IsRarityDepend = true,
                            IsStackable = false,
                            IsTradable = true,
                            IsUpgradable = true,
                            IsUsable = false,
                            Name = "Scratched Robe +9",
                            RequiredLevel = 0L,
                            UpgradeLevel = (byte)9,
                            Value = 450m,
                            DefenseValue = 64L,
                            EquippableBy = 2
                        });
                });

            modelBuilder.Entity("RpgGame.Models.Entity.MaterialPrototype", b =>
                {
                    b.HasBaseType("RpgGame.Models.Entity.ItemPrototype");

                    b.ToTable("MaterialPrototypes", "GAME");
                });

            modelBuilder.Entity("RpgGame.Models.Entity.WeaponPrototype", b =>
                {
                    b.HasBaseType("RpgGame.Models.Entity.ItemPrototype");

                    b.Property<int>("EquippableBy")
                        .HasColumnType("int");

                    b.Property<long>("MaxAttackValue")
                        .HasColumnType("bigint");

                    b.Property<long>("MinAttackValue")
                        .HasColumnType("bigint");

                    b.ToTable("WeaponPrototypes", "GAME");

                    b.HasData(
                        new
                        {
                            Id = 1000m,
                            IsEquippable = true,
                            IsRarityDepend = true,
                            IsStackable = false,
                            IsTradable = true,
                            IsUpgradable = true,
                            IsUsable = false,
                            Name = "Wooden Sword",
                            RequiredLevel = 0L,
                            UpgradeLevel = (byte)0,
                            Value = 10m,
                            EquippableBy = 0,
                            MaxAttackValue = 13L,
                            MinAttackValue = 10L
                        },
                        new
                        {
                            Id = 1001m,
                            IsEquippable = true,
                            IsRarityDepend = true,
                            IsStackable = false,
                            IsTradable = true,
                            IsUpgradable = true,
                            IsUsable = false,
                            Name = "Wooden Sword +1",
                            RequiredLevel = 0L,
                            UpgradeLevel = (byte)1,
                            Value = 50m,
                            EquippableBy = 0,
                            MaxAttackValue = 17L,
                            MinAttackValue = 14L
                        },
                        new
                        {
                            Id = 1002m,
                            IsEquippable = true,
                            IsRarityDepend = true,
                            IsStackable = false,
                            IsTradable = true,
                            IsUpgradable = true,
                            IsUsable = false,
                            Name = "Wooden Sword +2",
                            RequiredLevel = 0L,
                            UpgradeLevel = (byte)2,
                            Value = 100m,
                            EquippableBy = 0,
                            MaxAttackValue = 21L,
                            MinAttackValue = 18L
                        },
                        new
                        {
                            Id = 1003m,
                            IsEquippable = true,
                            IsRarityDepend = true,
                            IsStackable = false,
                            IsTradable = true,
                            IsUpgradable = true,
                            IsUsable = false,
                            Name = "Wooden Sword +3",
                            RequiredLevel = 0L,
                            UpgradeLevel = (byte)3,
                            Value = 150m,
                            EquippableBy = 0,
                            MaxAttackValue = 25L,
                            MinAttackValue = 22L
                        },
                        new
                        {
                            Id = 1004m,
                            IsEquippable = true,
                            IsRarityDepend = true,
                            IsStackable = false,
                            IsTradable = true,
                            IsUpgradable = true,
                            IsUsable = false,
                            Name = "Wooden Sword +4",
                            RequiredLevel = 0L,
                            UpgradeLevel = (byte)4,
                            Value = 200m,
                            EquippableBy = 0,
                            MaxAttackValue = 29L,
                            MinAttackValue = 26L
                        },
                        new
                        {
                            Id = 1005m,
                            IsEquippable = true,
                            IsRarityDepend = true,
                            IsStackable = false,
                            IsTradable = true,
                            IsUpgradable = true,
                            IsUsable = false,
                            Name = "Wooden Sword +5",
                            RequiredLevel = 0L,
                            UpgradeLevel = (byte)5,
                            Value = 250m,
                            EquippableBy = 0,
                            MaxAttackValue = 33L,
                            MinAttackValue = 30L
                        },
                        new
                        {
                            Id = 1006m,
                            IsEquippable = true,
                            IsRarityDepend = true,
                            IsStackable = false,
                            IsTradable = true,
                            IsUpgradable = true,
                            IsUsable = false,
                            Name = "Wooden Sword +6",
                            RequiredLevel = 0L,
                            UpgradeLevel = (byte)6,
                            Value = 300m,
                            EquippableBy = 0,
                            MaxAttackValue = 37L,
                            MinAttackValue = 34L
                        },
                        new
                        {
                            Id = 1007m,
                            IsEquippable = true,
                            IsRarityDepend = true,
                            IsStackable = false,
                            IsTradable = true,
                            IsUpgradable = true,
                            IsUsable = false,
                            Name = "Wooden Sword +7",
                            RequiredLevel = 0L,
                            UpgradeLevel = (byte)7,
                            Value = 350m,
                            EquippableBy = 0,
                            MaxAttackValue = 41L,
                            MinAttackValue = 38L
                        },
                        new
                        {
                            Id = 1008m,
                            IsEquippable = true,
                            IsRarityDepend = true,
                            IsStackable = false,
                            IsTradable = true,
                            IsUpgradable = true,
                            IsUsable = false,
                            Name = "Wooden Sword +8",
                            RequiredLevel = 0L,
                            UpgradeLevel = (byte)8,
                            Value = 400m,
                            EquippableBy = 0,
                            MaxAttackValue = 45L,
                            MinAttackValue = 42L
                        },
                        new
                        {
                            Id = 1009m,
                            IsEquippable = true,
                            IsRarityDepend = true,
                            IsStackable = false,
                            IsTradable = true,
                            IsUpgradable = true,
                            IsUsable = false,
                            Name = "Wooden Sword +9",
                            RequiredLevel = 0L,
                            UpgradeLevel = (byte)9,
                            Value = 450m,
                            EquippableBy = 0,
                            MaxAttackValue = 49L,
                            MinAttackValue = 46L
                        },
                        new
                        {
                            Id = 1010m,
                            IsEquippable = true,
                            IsRarityDepend = true,
                            IsStackable = false,
                            IsTradable = true,
                            IsUpgradable = true,
                            IsUsable = false,
                            Name = "Long Sword",
                            RequiredLevel = 5L,
                            UpgradeLevel = (byte)0,
                            Value = 20m,
                            EquippableBy = 0,
                            MaxAttackValue = 21L,
                            MinAttackValue = 18L
                        },
                        new
                        {
                            Id = 1011m,
                            IsEquippable = true,
                            IsRarityDepend = true,
                            IsStackable = false,
                            IsTradable = true,
                            IsUpgradable = true,
                            IsUsable = false,
                            Name = "Long Sword +1",
                            RequiredLevel = 5L,
                            UpgradeLevel = (byte)1,
                            Value = 75m,
                            EquippableBy = 0,
                            MaxAttackValue = 25L,
                            MinAttackValue = 22L
                        },
                        new
                        {
                            Id = 1012m,
                            IsEquippable = true,
                            IsRarityDepend = true,
                            IsStackable = false,
                            IsTradable = true,
                            IsUpgradable = true,
                            IsUsable = false,
                            Name = "Long Sword +2",
                            RequiredLevel = 5L,
                            UpgradeLevel = (byte)2,
                            Value = 150m,
                            EquippableBy = 0,
                            MaxAttackValue = 29L,
                            MinAttackValue = 26L
                        },
                        new
                        {
                            Id = 1013m,
                            IsEquippable = true,
                            IsRarityDepend = true,
                            IsStackable = false,
                            IsTradable = true,
                            IsUpgradable = true,
                            IsUsable = false,
                            Name = "Long Sword +3",
                            RequiredLevel = 5L,
                            UpgradeLevel = (byte)3,
                            Value = 225m,
                            EquippableBy = 0,
                            MaxAttackValue = 33L,
                            MinAttackValue = 30L
                        },
                        new
                        {
                            Id = 1014m,
                            IsEquippable = true,
                            IsRarityDepend = true,
                            IsStackable = false,
                            IsTradable = true,
                            IsUpgradable = true,
                            IsUsable = false,
                            Name = "Long Sword +4",
                            RequiredLevel = 5L,
                            UpgradeLevel = (byte)4,
                            Value = 300m,
                            EquippableBy = 0,
                            MaxAttackValue = 37L,
                            MinAttackValue = 34L
                        },
                        new
                        {
                            Id = 1015m,
                            IsEquippable = true,
                            IsRarityDepend = true,
                            IsStackable = false,
                            IsTradable = true,
                            IsUpgradable = true,
                            IsUsable = false,
                            Name = "Long Sword +5",
                            RequiredLevel = 5L,
                            UpgradeLevel = (byte)5,
                            Value = 375m,
                            EquippableBy = 0,
                            MaxAttackValue = 41L,
                            MinAttackValue = 38L
                        },
                        new
                        {
                            Id = 1016m,
                            IsEquippable = true,
                            IsRarityDepend = true,
                            IsStackable = false,
                            IsTradable = true,
                            IsUpgradable = true,
                            IsUsable = false,
                            Name = "Long Sword +6",
                            RequiredLevel = 5L,
                            UpgradeLevel = (byte)6,
                            Value = 450m,
                            EquippableBy = 0,
                            MaxAttackValue = 45L,
                            MinAttackValue = 42L
                        },
                        new
                        {
                            Id = 1017m,
                            IsEquippable = true,
                            IsRarityDepend = true,
                            IsStackable = false,
                            IsTradable = true,
                            IsUpgradable = true,
                            IsUsable = false,
                            Name = "Long Sword +7",
                            RequiredLevel = 5L,
                            UpgradeLevel = (byte)7,
                            Value = 525m,
                            EquippableBy = 0,
                            MaxAttackValue = 49L,
                            MinAttackValue = 46L
                        },
                        new
                        {
                            Id = 1018m,
                            IsEquippable = true,
                            IsRarityDepend = true,
                            IsStackable = false,
                            IsTradable = true,
                            IsUpgradable = true,
                            IsUsable = false,
                            Name = "Long Sword +8",
                            RequiredLevel = 5L,
                            UpgradeLevel = (byte)8,
                            Value = 600m,
                            EquippableBy = 0,
                            MaxAttackValue = 53L,
                            MinAttackValue = 50L
                        },
                        new
                        {
                            Id = 1019m,
                            IsEquippable = true,
                            IsRarityDepend = true,
                            IsStackable = false,
                            IsTradable = true,
                            IsUpgradable = true,
                            IsUsable = false,
                            Name = "Long Sword +9",
                            RequiredLevel = 5L,
                            UpgradeLevel = (byte)9,
                            Value = 675m,
                            EquippableBy = 0,
                            MaxAttackValue = 57L,
                            MinAttackValue = 54L
                        },
                        new
                        {
                            Id = 5000m,
                            IsEquippable = true,
                            IsRarityDepend = true,
                            IsStackable = false,
                            IsTradable = true,
                            IsUpgradable = true,
                            IsUsable = false,
                            Name = "Wooden Bow",
                            RequiredLevel = 0L,
                            UpgradeLevel = (byte)0,
                            Value = 10m,
                            EquippableBy = 1,
                            MaxAttackValue = 13L,
                            MinAttackValue = 10L
                        },
                        new
                        {
                            Id = 5001m,
                            IsEquippable = true,
                            IsRarityDepend = true,
                            IsStackable = false,
                            IsTradable = true,
                            IsUpgradable = true,
                            IsUsable = false,
                            Name = "Wooden Bow +1",
                            RequiredLevel = 0L,
                            UpgradeLevel = (byte)1,
                            Value = 50m,
                            EquippableBy = 1,
                            MaxAttackValue = 17L,
                            MinAttackValue = 14L
                        },
                        new
                        {
                            Id = 5002m,
                            IsEquippable = true,
                            IsRarityDepend = true,
                            IsStackable = false,
                            IsTradable = true,
                            IsUpgradable = true,
                            IsUsable = false,
                            Name = "Wooden Bow +2",
                            RequiredLevel = 0L,
                            UpgradeLevel = (byte)2,
                            Value = 100m,
                            EquippableBy = 1,
                            MaxAttackValue = 21L,
                            MinAttackValue = 18L
                        },
                        new
                        {
                            Id = 5003m,
                            IsEquippable = true,
                            IsRarityDepend = true,
                            IsStackable = false,
                            IsTradable = true,
                            IsUpgradable = true,
                            IsUsable = false,
                            Name = "Wooden Bow +3",
                            RequiredLevel = 0L,
                            UpgradeLevel = (byte)3,
                            Value = 150m,
                            EquippableBy = 1,
                            MaxAttackValue = 25L,
                            MinAttackValue = 22L
                        },
                        new
                        {
                            Id = 5004m,
                            IsEquippable = true,
                            IsRarityDepend = true,
                            IsStackable = false,
                            IsTradable = true,
                            IsUpgradable = true,
                            IsUsable = false,
                            Name = "Wooden Bow +4",
                            RequiredLevel = 0L,
                            UpgradeLevel = (byte)4,
                            Value = 200m,
                            EquippableBy = 1,
                            MaxAttackValue = 29L,
                            MinAttackValue = 26L
                        },
                        new
                        {
                            Id = 5005m,
                            IsEquippable = true,
                            IsRarityDepend = true,
                            IsStackable = false,
                            IsTradable = true,
                            IsUpgradable = true,
                            IsUsable = false,
                            Name = "Wooden Bow +5",
                            RequiredLevel = 0L,
                            UpgradeLevel = (byte)5,
                            Value = 250m,
                            EquippableBy = 1,
                            MaxAttackValue = 33L,
                            MinAttackValue = 30L
                        },
                        new
                        {
                            Id = 5006m,
                            IsEquippable = true,
                            IsRarityDepend = true,
                            IsStackable = false,
                            IsTradable = true,
                            IsUpgradable = true,
                            IsUsable = false,
                            Name = "Wooden Bow +6",
                            RequiredLevel = 0L,
                            UpgradeLevel = (byte)6,
                            Value = 300m,
                            EquippableBy = 1,
                            MaxAttackValue = 37L,
                            MinAttackValue = 34L
                        },
                        new
                        {
                            Id = 5007m,
                            IsEquippable = true,
                            IsRarityDepend = true,
                            IsStackable = false,
                            IsTradable = true,
                            IsUpgradable = true,
                            IsUsable = false,
                            Name = "Wooden Bow +7",
                            RequiredLevel = 0L,
                            UpgradeLevel = (byte)7,
                            Value = 350m,
                            EquippableBy = 1,
                            MaxAttackValue = 41L,
                            MinAttackValue = 38L
                        },
                        new
                        {
                            Id = 5008m,
                            IsEquippable = true,
                            IsRarityDepend = true,
                            IsStackable = false,
                            IsTradable = true,
                            IsUpgradable = true,
                            IsUsable = false,
                            Name = "Wooden Bow +8",
                            RequiredLevel = 0L,
                            UpgradeLevel = (byte)8,
                            Value = 400m,
                            EquippableBy = 1,
                            MaxAttackValue = 45L,
                            MinAttackValue = 42L
                        },
                        new
                        {
                            Id = 5009m,
                            IsEquippable = true,
                            IsRarityDepend = true,
                            IsStackable = false,
                            IsTradable = true,
                            IsUpgradable = true,
                            IsUsable = false,
                            Name = "Wooden Bow +9",
                            RequiredLevel = 0L,
                            UpgradeLevel = (byte)9,
                            Value = 450m,
                            EquippableBy = 1,
                            MaxAttackValue = 49L,
                            MinAttackValue = 46L
                        },
                        new
                        {
                            Id = 5010m,
                            IsEquippable = true,
                            IsRarityDepend = true,
                            IsStackable = false,
                            IsTradable = true,
                            IsUpgradable = true,
                            IsUsable = false,
                            Name = "Long Bow",
                            RequiredLevel = 5L,
                            UpgradeLevel = (byte)0,
                            Value = 20m,
                            EquippableBy = 1,
                            MaxAttackValue = 21L,
                            MinAttackValue = 18L
                        },
                        new
                        {
                            Id = 5011m,
                            IsEquippable = true,
                            IsRarityDepend = true,
                            IsStackable = false,
                            IsTradable = true,
                            IsUpgradable = true,
                            IsUsable = false,
                            Name = "Long Bow +1",
                            RequiredLevel = 5L,
                            UpgradeLevel = (byte)1,
                            Value = 75m,
                            EquippableBy = 1,
                            MaxAttackValue = 25L,
                            MinAttackValue = 22L
                        },
                        new
                        {
                            Id = 5012m,
                            IsEquippable = true,
                            IsRarityDepend = true,
                            IsStackable = false,
                            IsTradable = true,
                            IsUpgradable = true,
                            IsUsable = false,
                            Name = "Long Bow +2",
                            RequiredLevel = 5L,
                            UpgradeLevel = (byte)2,
                            Value = 150m,
                            EquippableBy = 1,
                            MaxAttackValue = 29L,
                            MinAttackValue = 26L
                        },
                        new
                        {
                            Id = 5013m,
                            IsEquippable = true,
                            IsRarityDepend = true,
                            IsStackable = false,
                            IsTradable = true,
                            IsUpgradable = true,
                            IsUsable = false,
                            Name = "Long Bow +3",
                            RequiredLevel = 5L,
                            UpgradeLevel = (byte)3,
                            Value = 225m,
                            EquippableBy = 1,
                            MaxAttackValue = 33L,
                            MinAttackValue = 30L
                        },
                        new
                        {
                            Id = 5014m,
                            IsEquippable = true,
                            IsRarityDepend = true,
                            IsStackable = false,
                            IsTradable = true,
                            IsUpgradable = true,
                            IsUsable = false,
                            Name = "Long Bow +4",
                            RequiredLevel = 5L,
                            UpgradeLevel = (byte)4,
                            Value = 300m,
                            EquippableBy = 1,
                            MaxAttackValue = 37L,
                            MinAttackValue = 34L
                        },
                        new
                        {
                            Id = 5015m,
                            IsEquippable = true,
                            IsRarityDepend = true,
                            IsStackable = false,
                            IsTradable = true,
                            IsUpgradable = true,
                            IsUsable = false,
                            Name = "Long Bow +5",
                            RequiredLevel = 5L,
                            UpgradeLevel = (byte)5,
                            Value = 375m,
                            EquippableBy = 1,
                            MaxAttackValue = 41L,
                            MinAttackValue = 38L
                        },
                        new
                        {
                            Id = 5016m,
                            IsEquippable = true,
                            IsRarityDepend = true,
                            IsStackable = false,
                            IsTradable = true,
                            IsUpgradable = true,
                            IsUsable = false,
                            Name = "Long Bow +6",
                            RequiredLevel = 5L,
                            UpgradeLevel = (byte)6,
                            Value = 450m,
                            EquippableBy = 1,
                            MaxAttackValue = 45L,
                            MinAttackValue = 42L
                        },
                        new
                        {
                            Id = 5017m,
                            IsEquippable = true,
                            IsRarityDepend = true,
                            IsStackable = false,
                            IsTradable = true,
                            IsUpgradable = true,
                            IsUsable = false,
                            Name = "Long Bow +7",
                            RequiredLevel = 5L,
                            UpgradeLevel = (byte)7,
                            Value = 525m,
                            EquippableBy = 1,
                            MaxAttackValue = 49L,
                            MinAttackValue = 46L
                        },
                        new
                        {
                            Id = 5018m,
                            IsEquippable = true,
                            IsRarityDepend = true,
                            IsStackable = false,
                            IsTradable = true,
                            IsUpgradable = true,
                            IsUsable = false,
                            Name = "Long Bow +8",
                            RequiredLevel = 5L,
                            UpgradeLevel = (byte)8,
                            Value = 600m,
                            EquippableBy = 1,
                            MaxAttackValue = 53L,
                            MinAttackValue = 50L
                        },
                        new
                        {
                            Id = 5019m,
                            IsEquippable = true,
                            IsRarityDepend = true,
                            IsStackable = false,
                            IsTradable = true,
                            IsUpgradable = true,
                            IsUsable = false,
                            Name = "Long Bow +9",
                            RequiredLevel = 5L,
                            UpgradeLevel = (byte)9,
                            Value = 675m,
                            EquippableBy = 1,
                            MaxAttackValue = 57L,
                            MinAttackValue = 54L
                        },
                        new
                        {
                            Id = 9000m,
                            IsEquippable = true,
                            IsRarityDepend = true,
                            IsStackable = false,
                            IsTradable = true,
                            IsUpgradable = true,
                            IsUsable = false,
                            Name = "Wooden Staff",
                            RequiredLevel = 0L,
                            UpgradeLevel = (byte)0,
                            Value = 10m,
                            EquippableBy = 2,
                            MaxAttackValue = 13L,
                            MinAttackValue = 10L
                        },
                        new
                        {
                            Id = 9001m,
                            IsEquippable = true,
                            IsRarityDepend = true,
                            IsStackable = false,
                            IsTradable = true,
                            IsUpgradable = true,
                            IsUsable = false,
                            Name = "Wooden Staff +1",
                            RequiredLevel = 0L,
                            UpgradeLevel = (byte)1,
                            Value = 50m,
                            EquippableBy = 2,
                            MaxAttackValue = 17L,
                            MinAttackValue = 14L
                        },
                        new
                        {
                            Id = 9002m,
                            IsEquippable = true,
                            IsRarityDepend = true,
                            IsStackable = false,
                            IsTradable = true,
                            IsUpgradable = true,
                            IsUsable = false,
                            Name = "Wooden Staff +2",
                            RequiredLevel = 0L,
                            UpgradeLevel = (byte)2,
                            Value = 100m,
                            EquippableBy = 2,
                            MaxAttackValue = 21L,
                            MinAttackValue = 18L
                        },
                        new
                        {
                            Id = 9003m,
                            IsEquippable = true,
                            IsRarityDepend = true,
                            IsStackable = false,
                            IsTradable = true,
                            IsUpgradable = true,
                            IsUsable = false,
                            Name = "Wooden Staff +3",
                            RequiredLevel = 0L,
                            UpgradeLevel = (byte)3,
                            Value = 150m,
                            EquippableBy = 2,
                            MaxAttackValue = 25L,
                            MinAttackValue = 22L
                        },
                        new
                        {
                            Id = 9004m,
                            IsEquippable = true,
                            IsRarityDepend = true,
                            IsStackable = false,
                            IsTradable = true,
                            IsUpgradable = true,
                            IsUsable = false,
                            Name = "Wooden Staff +4",
                            RequiredLevel = 0L,
                            UpgradeLevel = (byte)4,
                            Value = 200m,
                            EquippableBy = 2,
                            MaxAttackValue = 29L,
                            MinAttackValue = 26L
                        },
                        new
                        {
                            Id = 9005m,
                            IsEquippable = true,
                            IsRarityDepend = true,
                            IsStackable = false,
                            IsTradable = true,
                            IsUpgradable = true,
                            IsUsable = false,
                            Name = "Wooden Staff +5",
                            RequiredLevel = 0L,
                            UpgradeLevel = (byte)5,
                            Value = 250m,
                            EquippableBy = 2,
                            MaxAttackValue = 33L,
                            MinAttackValue = 30L
                        },
                        new
                        {
                            Id = 9006m,
                            IsEquippable = true,
                            IsRarityDepend = true,
                            IsStackable = false,
                            IsTradable = true,
                            IsUpgradable = true,
                            IsUsable = false,
                            Name = "Wooden Staff +6",
                            RequiredLevel = 0L,
                            UpgradeLevel = (byte)6,
                            Value = 300m,
                            EquippableBy = 2,
                            MaxAttackValue = 37L,
                            MinAttackValue = 34L
                        },
                        new
                        {
                            Id = 9007m,
                            IsEquippable = true,
                            IsRarityDepend = true,
                            IsStackable = false,
                            IsTradable = true,
                            IsUpgradable = true,
                            IsUsable = false,
                            Name = "Wooden Staff +7",
                            RequiredLevel = 0L,
                            UpgradeLevel = (byte)7,
                            Value = 350m,
                            EquippableBy = 2,
                            MaxAttackValue = 41L,
                            MinAttackValue = 38L
                        },
                        new
                        {
                            Id = 9008m,
                            IsEquippable = true,
                            IsRarityDepend = true,
                            IsStackable = false,
                            IsTradable = true,
                            IsUpgradable = true,
                            IsUsable = false,
                            Name = "Wooden Staff +8",
                            RequiredLevel = 0L,
                            UpgradeLevel = (byte)8,
                            Value = 400m,
                            EquippableBy = 2,
                            MaxAttackValue = 45L,
                            MinAttackValue = 42L
                        },
                        new
                        {
                            Id = 9009m,
                            IsEquippable = true,
                            IsRarityDepend = true,
                            IsStackable = false,
                            IsTradable = true,
                            IsUpgradable = true,
                            IsUsable = false,
                            Name = "Wooden Staff +9",
                            RequiredLevel = 0L,
                            UpgradeLevel = (byte)9,
                            Value = 450m,
                            EquippableBy = 2,
                            MaxAttackValue = 49L,
                            MinAttackValue = 46L
                        },
                        new
                        {
                            Id = 9010m,
                            IsEquippable = true,
                            IsRarityDepend = true,
                            IsStackable = false,
                            IsTradable = true,
                            IsUpgradable = true,
                            IsUsable = false,
                            Name = "Long Staff",
                            RequiredLevel = 5L,
                            UpgradeLevel = (byte)0,
                            Value = 20m,
                            EquippableBy = 2,
                            MaxAttackValue = 21L,
                            MinAttackValue = 18L
                        },
                        new
                        {
                            Id = 9011m,
                            IsEquippable = true,
                            IsRarityDepend = true,
                            IsStackable = false,
                            IsTradable = true,
                            IsUpgradable = true,
                            IsUsable = false,
                            Name = "Long Staff +1",
                            RequiredLevel = 5L,
                            UpgradeLevel = (byte)1,
                            Value = 75m,
                            EquippableBy = 2,
                            MaxAttackValue = 25L,
                            MinAttackValue = 22L
                        },
                        new
                        {
                            Id = 9012m,
                            IsEquippable = true,
                            IsRarityDepend = true,
                            IsStackable = false,
                            IsTradable = true,
                            IsUpgradable = true,
                            IsUsable = false,
                            Name = "Long Staff +2",
                            RequiredLevel = 5L,
                            UpgradeLevel = (byte)2,
                            Value = 150m,
                            EquippableBy = 2,
                            MaxAttackValue = 29L,
                            MinAttackValue = 26L
                        },
                        new
                        {
                            Id = 9013m,
                            IsEquippable = true,
                            IsRarityDepend = true,
                            IsStackable = false,
                            IsTradable = true,
                            IsUpgradable = true,
                            IsUsable = false,
                            Name = "Long Staff +3",
                            RequiredLevel = 5L,
                            UpgradeLevel = (byte)3,
                            Value = 225m,
                            EquippableBy = 2,
                            MaxAttackValue = 33L,
                            MinAttackValue = 30L
                        },
                        new
                        {
                            Id = 9014m,
                            IsEquippable = true,
                            IsRarityDepend = true,
                            IsStackable = false,
                            IsTradable = true,
                            IsUpgradable = true,
                            IsUsable = false,
                            Name = "Long Staff +4",
                            RequiredLevel = 5L,
                            UpgradeLevel = (byte)4,
                            Value = 300m,
                            EquippableBy = 2,
                            MaxAttackValue = 37L,
                            MinAttackValue = 34L
                        },
                        new
                        {
                            Id = 9015m,
                            IsEquippable = true,
                            IsRarityDepend = true,
                            IsStackable = false,
                            IsTradable = true,
                            IsUpgradable = true,
                            IsUsable = false,
                            Name = "Long Staff +5",
                            RequiredLevel = 5L,
                            UpgradeLevel = (byte)5,
                            Value = 375m,
                            EquippableBy = 2,
                            MaxAttackValue = 41L,
                            MinAttackValue = 38L
                        },
                        new
                        {
                            Id = 9016m,
                            IsEquippable = true,
                            IsRarityDepend = true,
                            IsStackable = false,
                            IsTradable = true,
                            IsUpgradable = true,
                            IsUsable = false,
                            Name = "Long Staff +6",
                            RequiredLevel = 5L,
                            UpgradeLevel = (byte)6,
                            Value = 450m,
                            EquippableBy = 2,
                            MaxAttackValue = 45L,
                            MinAttackValue = 42L
                        },
                        new
                        {
                            Id = 9017m,
                            IsEquippable = true,
                            IsRarityDepend = true,
                            IsStackable = false,
                            IsTradable = true,
                            IsUpgradable = true,
                            IsUsable = false,
                            Name = "Long Staff +7",
                            RequiredLevel = 5L,
                            UpgradeLevel = (byte)7,
                            Value = 525m,
                            EquippableBy = 2,
                            MaxAttackValue = 49L,
                            MinAttackValue = 46L
                        },
                        new
                        {
                            Id = 9018m,
                            IsEquippable = true,
                            IsRarityDepend = true,
                            IsStackable = false,
                            IsTradable = true,
                            IsUpgradable = true,
                            IsUsable = false,
                            Name = "Long Staff +8",
                            RequiredLevel = 5L,
                            UpgradeLevel = (byte)8,
                            Value = 600m,
                            EquippableBy = 2,
                            MaxAttackValue = 53L,
                            MinAttackValue = 50L
                        },
                        new
                        {
                            Id = 9019m,
                            IsEquippable = true,
                            IsRarityDepend = true,
                            IsStackable = false,
                            IsTradable = true,
                            IsUpgradable = true,
                            IsUsable = false,
                            Name = "Long Staff +9",
                            RequiredLevel = 5L,
                            UpgradeLevel = (byte)9,
                            Value = 675m,
                            EquippableBy = 2,
                            MaxAttackValue = 57L,
                            MinAttackValue = 54L
                        });
                });

            modelBuilder.Entity("RpgGame.Models.Entity.Character", b =>
                {
                    b.HasOne("RpgGame.Models.Entity.User", "User")
                        .WithMany("Characters")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RpgGame.Models.Entity.Inventory", b =>
                {
                    b.HasOne("RpgGame.Models.Entity.Character", "Character")
                        .WithOne("Inventory")
                        .HasForeignKey("RpgGame.Models.Entity.Inventory", "CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("RpgGame.Models.Entity.Item", b =>
                {
                    b.HasOne("RpgGame.Models.Entity.Inventory", "Inventory")
                        .WithMany("Items")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RpgGame.Models.Entity.ItemPrototype", "ItemPrototype")
                        .WithMany()
                        .HasForeignKey("ItemPrototypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventory");

                    b.Navigation("ItemPrototype");
                });

            modelBuilder.Entity("RpgGame.Models.Entity.Character", b =>
                {
                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("RpgGame.Models.Entity.Inventory", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("RpgGame.Models.Entity.User", b =>
                {
                    b.Navigation("Characters");
                });
#pragma warning restore 612, 618
        }
    }
}
